version: '3.8'

services:

  oeweb_api_dev:
    image: aledpv/oeweb-api:4.0.73.14
    container_name: oeweb_api_dev_4.0.73.14
    hostname: oeweb_api_dev_4.0.73.14
    dns:
      - "172.30.1.20"
    dns_search:
      - "pottsmullarkey.com"
    ports:
      - "9000:80"
    networks:
      - internal

  oeweb_rs_dev:
    image: aledpv/oeweb-rs:4.0.73.14
    container_name: oeweb_rs_dev_4.0.73.14
    hostname: oeweb_rs_dev_4.0.73.14
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"   
    ports:
      - "9082:9082"
      - "9083:9083" 
    networks:
      - internal
    volumes:
      - 'C:\temp\DreamReg:C:\config'
      - 'C:\users\aledh\.aws:C:\users\containeradministrator\.aws'
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - PLOT_CONFIG_SOURCE=s3://pv-plot-configuration/dev
      - 'PLOT_CONFIG_TARGET=C:\Program Files (x86)\OE Accounts Remoting\OERemotingService.exe.config'

  plot_rs_dev:
    image: aledpv/plot-rs:4.0.73.14
    container_name: plot_rs_dev_4.0.73.14
    hostname: plot_rs_dev_4.0.73.14
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"    
    ports:
      - "8082:8082"
      - "8083:8083" 
      - "8084:8084"
    networks:
      - internal
    volumes:
      - 'C:\temp\DreamReg:C:\config'
      - 'C:\users\aledh\.aws:C:\users\containeradministrator\.aws'
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - PLOT_CONFIG_SOURCE=s3://pv-plot-configuration/dev
      - 'PLOT_CONFIG_TARGET=C:\Program Files (x86)\Plot Control Remoting Server\SiConRemotingService.exe.config'

  plot_rs_dev_uploader:
    image: aledpv/plot-rs:4.0.73.14
    container_name: plot_rs_dev_uploader_4.0.73.14
    hostname: plot_rs_dev_uploader_4.0.73.14
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"    
    ports:
      - "8182:8082"
      - "8183:8083" 
      - "8184:8084"
    networks:
      - internal
    volumes:
      - 'C:\temp\DreamReg:C:\config'
      - 'C:\users\aledh\.aws:C:\users\containeradministrator\.aws'
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - PLOT_CONFIG_SOURCE=s3://pv-plot-configuration/dev/uploader
      - 'PLOT_CONFIG_TARGET=C:\Program Files (x86)\Plot Control Remoting Server\SiConRemotingService.exe.config'

  plot_rs_dev_scheduler:
    image: aledpv/plot-rs:4.0.73.14
    container_name: plot_rs_dev_scheduler_4.0.73.14
    hostname: plot_rs_dev_scheduler_4.0.73.14
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"    
    ports:
      - "8282:8082"
      - "8283:8083" 
      - "8284:8084"
    networks:
      - internal
    volumes:
      - 'C:\temp\DreamReg:C:\config'
      - 'C:\users\aledh\.aws:C:\users\containeradministrator\.aws'
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - PLOT_CONFIG_SOURCE=s3://pv-plot-configuration/dev/scheduler
      - 'PLOT_CONFIG_TARGET=C:\Program Files (x86)\Plot Control Remoting Server\SiConRemotingService.exe.config'

networks:
  external:
    name: external
  internal:
    name: internal