version: '3.8'

services:
  # iiscore:
  #   build:
  #     context: ./iiscore/
  #   image: 327322993001.dkr.ecr.eu-west-1.amazonaws.com/iiscore:latest
  #   ports:
  #     - "80:80"
  #   networks:
  #     - external

  # oeaccountservice:
  #   build:
  #     context: ./oeaccountservice/
  #   image: 327322993001.dkr.ecr.eu-west-1.amazonaws.com/oeaccountservice:latest
  #   ports:
  #     - "9082:9082"
  #     - "9083:9083"
  #   networks:
  #     - internal

  # prospectservice:
  #   build:
  #     context: ./prospectservice/
  #   image: 327322993001.dkr.ecr.eu-west-1.amazonaws.com/prospectservice:latest
  #   ports:
  #     - "9092:9092"
  #   networks:
  #     - internal

  oeweb_api_dev:
    image: oeweb-api:latestDev
    container_name: oeweb_api_dev
    hostname: oeweb_api_dev
    dns:
      - "172.30.1.20"
    dns_search:
      - "pottsmullarkey.com"
    ports:
      - "9000:80"
    networks:
      - internal

  oeweb_rs_dev:
    image: oeweb-rs:latestDev
    container_name: oeweb_rs_dev
    hostname: oeweb_rs_dev
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"   
    ports:
      - "9082:9082"
      - "9083:9083" 
    networks:
      - internal
    volumes:
      - 'C:\temp\DreamReg:C:\config'

  plot_rs_dev:
  #  build:
  #    context: ./plot_rs/
    image: plot-rs:latestDev
    container_name: plot_rs_dev
    hostname: plot_rs_dev
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"    
    ports:
      - "8082:8082"
      - "8083:8083" 
      - "8084:8084"
    networks:
      - internal
    volumes:
      - 'C:\temp\DreamReg:C:\config'

networks:
  external:
    name: external
  internal:
    name: internal

x-aws-vpc: "vpc-0f896c0859cbf92d3"

x-aws-cloudformation:
  Resources:
    OeaccountserviceTaskDefinition:
      Properties:
        RuntimePlatform:
          OperatingSystemFamily: WINDOWS_SERVER_2022_CORE
    OewebservicesTaskDefinition:
      Properties:
        RuntimePlatform:
          OperatingSystemFamily: WINDOWS_SERVER_2022_CORE
