version: '3.8'

services:

  plot-api:
    image: aledpv/plot-api:${VERSION}
    container_name: plot_api_test${VERSION}
    hostname: plot_api_test${VERSION}
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"    
    ports:
      - "9022:80"
    networks:
      - internal
    volumes:
      - 'C:\users\aledh\.aws:C:\users\containeradministrator\.aws'
    environment:
      - ASPNETCORE_ENVIRONMENT=test
    depends_on:
      init_db_migration:
        condition: service_completed_successfully

  init_db_migration:
    image: aledpv/dbmigrator
    dns:
       - "172.30.1.20"
    dns_search:
       - "pottsmullarkey.com"
    networks:
      - internal
    volumes:
      - 'C:\users\aledh\.aws:C:\users\containeruser\.aws'
    environment:
      - TARGET_VERSION=${VERSION}
      - REPO_URL=${REPO_URL}
      - REPO_PAT=${REPO_PAT}
      - REPO_SCRIPTS_DIR=${REPO_SCRIPTS_DIR}
      - AWS_CONFIG_SOURCE=s3://pv-plot-configuration/environment/test
      - AWS_CONFIG_TARGET=C:\app\dbmigrator.connection.config
      - XML_CONFIG_PATH=C:\app\dbmigrator.connection.config
      - XML_CONFIG_CONNECTION_STRING_XPATH=//configuration/appSettings/add[@key='Ekto.Plot_CurrentTest_ConnectionStringSiCon']
      - XML_CONFIG_CONNECTION_STRING_ATTR_KEY=value
      - CONTROL_NAME=PlotAPI

networks:
  external:
    name: external
  internal:
    name: internal